language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

env:
  - COVERAGE=0.5
  - TARGET=ui
  - TARGET=service/card
  - TARGET=service/user
  - TARGET=repository/order
  - TARGET=repository/cart
  - TARGET=repository/product
  - TARGET=repository/user

jobs:
  include:
    - stage: build
      script: ./gradlew clean jar
    - stage: deploy
      install: skip
      before_deploy:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      deploy:
        provider: script
        script:
          - script: echo 'WIP'
